---
# tasks file for ansible-java
- name: install required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - unzip

- name: check if it is present
  stat: path=/usr/bin/java
  register: java_present

- name: add apt repository
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: accept Oracle license before an installation
  shell: echo "oracle-java{{ oracle_java_version }}-installer shared/accepted-oracle-license-v1-1 select true" | /usr/bin/debconf-set-selections
  when: java_present.stat.exists == False

- name: install
  apt:
    update-cache: yes
    force: yes
    state: present
    pkg: "oracle-java{{ oracle_java_version }}-installer"
  when: java_present.stat.exists == False
