---
- name: download java rpm
  uri:
    url: "{{ oracle_java_rpm_url }}"
    method: GET
    HEADER_Content_-Type: Cookie:oraclelicense=accept-securebackup-cookie
    dest: "/tmp/{{ oracle_java_rpm_filename }}"
    creates: "/tmp/{{ oracle_java_rpm_filename }}"
  register: java_rpm

- name: install java rpm
  yum:
    name: "/tmp/{{ oracle_java_rpm_filename }}"
    state: present
  when: java_rpm

- name: set oracle as a default
  alternatives:
    name: "{{ item }}"
    link: "/usr/bin/{{ item }}"
  with_items:
    - { path: "{{ oracle_java_home }}/jre/bin", item: 'java' }
    - { path: "{{ oracle_java_home }}/jre/bin", item: 'keytool' }
    - { path: "{{ oracle_java_home }}/bin", item: 'javac' }
    - { path: "{{ oracle_java_home }}/bin", item: 'java' }
