---
# - name: download java rpm
#   uri:
#     url: "{{ oracle_java_rpm_url }}"
#     method: GET
#     HEADER_Content_-Type: Cookie:oraclelicense=accept-securebackup-cookie
#     follow_redirects: safe
#     dest: "/tmp/{{ oracle_java_rpm_filename }}"
#     creates: "/tmp/{{ oracle_java_rpm_filename }}"
#   register: java_rpm
- name: install curl
  yum:
    name: curl
    state: installed

- name: download java rpm
  shell:
    "curl -L -H 'Cookie:oraclelicense=accept-securebackup-cookie' -o /tmp/{{ oracle_java_rpm_filename }} {{ oracle_java_rpm_url }}"
  args:
    creates: "tmp/{{ oracle_java_rpm_filename }}"
  register: java_rpm

- name: install java rpm
  yum:
    name: "/tmp/{{ oracle_java_rpm_filename }}"
    state: present
  when: java_rpm

- name: set oracle as a default
  alternatives:
    name: "{{ item.bin }}"
    link: "/usr/bin/{{ item.bin }}"
    path: "{{ item.path }}/{{ item.bin }}"
  with_items:
    - { path: "{{ oracle_java_home }}/jre/bin", bin: 'java' }
    - { path: "{{ oracle_java_home }}/jre/bin", bin: 'keytool' }
    - { path: "{{ oracle_java_home }}/bin", bin: 'javac' }
    - { path: "{{ oracle_java_home }}/bin", bin: 'java' }
