---
- name: create jce path
  set_fact:
    jce_location: "{{ oracle_jce_home }}-{{ oracle_java_version }}"

- name: create jce home
  file:
    path: "{{ jce_location }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: download oracle_jce
  command: curl -L -H 'Cookie:oraclelicense=accept-securebackup-cookie' -o /tmp/jce-{{ oracle_java_version }}.zip {{ oracle_jce_url }}
  args:
    creates: /tmp/jce-{{ oracle_java_version }}.zip

- name: extract jce zip file
  command: unzip -j /tmp/jce-{{ oracle_java_version }}.zip -d {{ jce_location }}
  args:
    creates: "{{ jce_location }}/local_policy.jar"

- name: set jar file permissions
  file:
    path: "{{ jce_location }}/{{ item }}"
    state: touch
    mode: "0755"
  with_items:
    - local_policy.jar
    - US_export_policy.jar
