---
# tasks file for ansible-java
- name: collect facts
  setup:

- include_vars: "{{ ansible_os_family }}.yml"

- name: output facts
  debug:
    var: ansible_os_family

- include: "tasks/install-{{ ansible_os_family }}-java.yml"
- include: "tasks/jce.yml"
